steps:
  - name: 'google/cloud-sdk:258.0.0-alpine'
    args: [
    'gcloud', 'config', 'set', 'core/project', $_PROJECT_ID, '&&',
    'gcloud', 'container', 'clusters', ' get-credentials', $_CLUSTER_NAME, '&&',
    'kubectl', 'apply', '-f', '.', '-R'
    ]
    id: apply
