steps:
  - name: 'hashicorp/terraform:0.12.7'
    args: ['workspace', 'select', $_WORKSPACE]
  - name: 'hashicorp/terraform:0.12.7'
    args: ['plan']
  - name: 'hashicorp/terraform:0.12.7'
    args: ['apply',', '-auto-approve']
    id: terraform-apply
