steps:
  - name: 'google/cloud-sdk:258.0.0-alpine'
    args: ['gcloud', 'config', 'set', ${_PROJECT_ID}]
    id: set-config
  - name: 'google/cloud-sdk:258.0.0-alpine'
    args: ['gcloud', 'container', 'clusters', ' get-credentials', ${_CLUSTER_NAME}]
    id: get-credential
  - name: 'google/cloud-sdk:258.0.0-alpine'
    args: ['kubectl', 'apply', '-f', '.', '-R']
    id: apply
