steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['kubectl', 'apply', '-f', '.']
    env:
    - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
    - 'CLOUDSDK_CORE_PROJECT=$_PROJECT_ID'
    id: apply
